import { createWriteStream, mkdtempSync, rmSync } from "node:fs";
import { readFile, unlink } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, join } from "node:path";
import yauzl from "yauzl";
import { checkStorageQuota, createRecording, DuplicateError, QuotaError } from "./recordings";

// Google's auto-generated recording name, e.g. "22 Nov at 19_40" or
// "22 Nov at 19_40(1)" (the "(1)" suffix Google itself appends when two
// recordings land in the same minute). No year, only minute resolution, so
// this can never be trusted as a real date, only as a "is this a real title
// or not" signal.
const AUTO_TITLE_PATTERN = /^\d{1,2} [A-Za-z]{3} at \d{2}_\d{2}(\(\d+\))?$/;
const SUMMARY_SUFFIX = "_summary.txt";
const AUDIO_EXTENSIONS = new Set(["m4a", "mp3", "wav", "ogg", "flac", "webm"]);
const MIME_TYPES: Record<string, string> = {
	m4a: "audio/mp4",
	mp3: "audio/mpeg",
	wav: "audio/wav",
	ogg: "audio/ogg",
	flac: "audio/flac",
	webm: "audio/webm"
};

export type ImportJobStatus = "processing" | "done" | "failed";

export interface ImportJob {
	id: string;
	userId: string;
	status: ImportJobStatus;
	total: number;
	processed: number;
	imported: number;
	duplicates: number;
	errors: number;
	errorMessages: string[];
	quotaReached: boolean;
	// Fun stats about the imported batch, for the "import complete" screen.
	totalDurationSeconds: number;
	transcribedCount: number;
	earliestDate: string | null;
	latestDate: string | null;
}

const jobs = new Map<string, ImportJob>();

function isAutoGeneratedTitle(name: string): boolean {
	return AUTO_TITLE_PATTERN.test(name.trim());
}

async function ffprobeMeta(filePath: string): Promise<{ createdAt: string | null; durationSeconds: number }> {
	const proc = Bun.spawn(
		["ffprobe", "-v", "error", "-show_entries", "format=duration:format_tags=creation_time", "-of", "json", filePath],
		{ stdout: "pipe", stderr: "ignore" }
	);
	const output = await new Response(proc.stdout).text();
	await proc.exited;

	try {
		const data = JSON.parse(output);
		const createdAt = typeof data.format?.tags?.creation_time === "string" ? data.format.tags.creation_time : null;
		const durationSeconds = Number(data.format?.duration ?? 0) || 0;
		return { createdAt, durationSeconds };
	} catch {
		return { createdAt: null, durationSeconds: 0 };
	}
}

interface ManifestEntry {
	audioPath: string;
	ext: string;
}

// Reads every entry once: audio files stream straight to a temp file on disk
// (never buffered in memory), transcript text files are tiny so they're
// buffered directly. Nothing here loads the whole archive into memory at
// once, only ever one entry's worth of streaming at a time.
function extractZip(zipPath: string, workDir: string): Promise<{ manifest: Map<string, ManifestEntry>; transcripts: Map<string, string> }> {
	const manifest = new Map<string, ManifestEntry>();
	const transcripts = new Map<string, string>();

	return new Promise((resolve, reject) => {
		yauzl.open(zipPath, { lazyEntries: true }, (err, zipfile) => {
			if (err || !zipfile) {
				reject(err ?? new Error("Failed to open the Takeout archive"));
				return;
			}

			zipfile.readEntry();

			zipfile.on("entry", (entry) => {
				const name = entry.fileName;
				if (name.endsWith("/")) {
					zipfile.readEntry();
					return;
				}

				const base = basename(name);

				if (base.endsWith(SUMMARY_SUFFIX)) {
					const key = base.slice(0, -SUMMARY_SUFFIX.length);
					zipfile.openReadStream(entry, (err, readStream) => {
						if (err || !readStream) {
							zipfile.readEntry();
							return;
						}
						const chunks: Buffer[] = [];
						readStream.on("data", (chunk) => chunks.push(chunk as Buffer));
						readStream.on("end", () => {
							transcripts.set(key, Buffer.concat(chunks).toString("utf-8").trim());
							zipfile.readEntry();
						});
						readStream.on("error", () => zipfile.readEntry());
					});
					return;
				}

				const dot = base.lastIndexOf(".");
				const ext = dot === -1 ? "" : base.slice(dot + 1).toLowerCase();

				if (AUDIO_EXTENSIONS.has(ext)) {
					const key = base.slice(0, dot);
					const tempPath = join(workDir, `${crypto.randomUUID()}.${ext}`);
					zipfile.openReadStream(entry, (err, readStream) => {
						if (err || !readStream) {
							zipfile.readEntry();
							return;
						}
						const writeStream = createWriteStream(tempPath);
						readStream.pipe(writeStream);
						writeStream.on("finish", () => {
							manifest.set(key, { audioPath: tempPath, ext });
							zipfile.readEntry();
						});
						writeStream.on("error", () => zipfile.readEntry());
					});
					return;
				}

				zipfile.readEntry();
			});

			zipfile.on("end", () => resolve({ manifest, transcripts }));
			zipfile.on("error", reject);
		});
	});
}

async function runImport(job: ImportJob, userId: string, userStorageLimitMb: number | null, zipPath: string) {
	const workDir = mkdtempSync(join(tmpdir(), "recoral-takeout-"));

	try {
		const { manifest, transcripts } = await extractZip(zipPath, workDir);
		job.total = manifest.size;

		for (const [name, { audioPath, ext }] of manifest) {
			try {
				const stats = await readFile(audioPath);
				checkStorageQuota(userId, userStorageLimitMb, stats.byteLength);

				const { createdAt, durationSeconds } = await ffprobeMeta(audioPath);
				const title = isAutoGeneratedTitle(name) ? "" : name;
				const transcript = transcripts.get(name) ?? null;
				const file = new File([stats], `${name}.${ext}`, { type: MIME_TYPES[ext] ?? "audio/mpeg" });

				await createRecording({
					userId,
					title,
					file,
					durationSeconds,
					createdAt: createdAt ?? undefined,
					transcript
				});

				job.imported++;
				job.totalDurationSeconds += durationSeconds;
				if (transcript) job.transcribedCount++;
				if (createdAt) {
					if (!job.earliestDate || createdAt < job.earliestDate) job.earliestDate = createdAt;
					if (!job.latestDate || createdAt > job.latestDate) job.latestDate = createdAt;
				}
			} catch (err) {
				if (err instanceof DuplicateError) {
					job.duplicates++;
				} else if (err instanceof QuotaError) {
					job.quotaReached = true;
					job.errorMessages.push(err.message);
					unlink(audioPath).catch(() => {});
					break;
				} else {
					job.errors++;
					job.errorMessages.push(`${name}: ${(err as Error).message}`);
				}
			} finally {
				job.processed++;
				unlink(audioPath).catch(() => {});
			}
		}

		job.status = "done";
	} catch (err) {
		job.status = "failed";
		job.errorMessages.push((err as Error).message);
	} finally {
		rmSync(workDir, { recursive: true, force: true });
		unlink(zipPath).catch(() => {});
	}
}

export function startTakeoutImport(userId: string, userStorageLimitMb: number | null, zipPath: string): string {
	const jobId = crypto.randomUUID();
	const job: ImportJob = {
		id: jobId,
		userId,
		status: "processing",
		total: 0,
		processed: 0,
		imported: 0,
		duplicates: 0,
		errors: 0,
		errorMessages: [],
		quotaReached: false,
		totalDurationSeconds: 0,
		transcribedCount: 0,
		earliestDate: null,
		latestDate: null
	};
	jobs.set(jobId, job);

	runImport(job, userId, userStorageLimitMb, zipPath).catch((err) => {
		job.status = "failed";
		job.errorMessages.push((err as Error).message);
	});

	return jobId;
}

export function getImportJob(userId: string, jobId: string): ImportJob | null {
	const job = jobs.get(jobId);
	return job && job.userId === userId ? job : null;
}
